### ISSUE TITLE
OpenStudio_Toolkit: Namespace update to `Adapters`

### ISSUE THREAD

**Issue by alelom** [BHoM/OpenStudio_Toolkit#36]
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.OpenStudio` or `BH.Engine.Adapters.OpenStudio` instead of `BH.oM.OpenStudio`, etc.

The Adapter namespace should remain at `BH.Adapter.OpenStudio` instead of `BH.Adapter.External.OpenStudio`.

**ALSO make sure that the default namespace is set correctly in the oM and Engine Project properties.**
➡️ [Right click on the project, navigate to the Application tab, and check the default namespace](https://user-images.githubusercontent.com/6352844/90246499-b122da00-de2c-11ea-92c0-edf0fcf81584.png).

#### Suggestions to restore compliance:

As above.

**Comment by alelom** [comment]
Reminder - I'd like to close this ASAP 😄

**Comment by FraserGreenroyd** [comment]
@alelom this isn't in an installer so this has the lowest of priorities from our teams side of things at the moment I'm afraid
